make all:
	g++ -std=c++11 -o serverA serverA.cpp
	g++ -std=c++11 -o serverB serverB.cpp
	g++ -std=c++11 -o servermain servermain.cpp
	g++ -std=c++11 -o client client.cpp

clean:
	rm -f *.o
	$(RM) serverA serverB servermain client